Task2b
Mayden-Academy/2020-feb-propertyListing pull request #3
Opened 2020-05-04 14:14 UTC by danicatt

2020-05-04 15:28 UTC, Sen-i requested changes
Are the interfaces not implemented for a reason?

2020-05-04 15:28 UTC, Sen-i commented on src/Collections/PropertyCollection.php
> +                throw new \Exception('Array must only contain instances of PropertyEntity');
What does the \ do here ?
can it be 
```suggestion
                throw new Exception('Array must only contain instances of PropertyEntity');
```

2020-05-04 15:28 UTC, Sen-i commented on src/Collections/PropertyCollection.php
> +                throw new \Exception('Array must only contain instances of PropertyEntity');
ohh it is related to namesapce!?

2020-05-04 15:28 UTC, Sen-i commented on src/Hydrators/PropertyHydrator.php
> +    private $database;
whiteSpace
```suggestion
   private $database;
```

2020-05-04 15:28 UTC, Sen-i commented on src/Entities/PropertyEntity.php
> +
```suggestion

```
WhiteSpace

2020-05-04 15:28 UTC, Sen-i commented on src/Hydrators/PropertyHydrator.php
> +
```suggestion

```
WhiteSpace

2020-05-04 15:28 UTC, Sen-i commented on src/Hydrators/PropertyHydrator.php
> +
```suggestion

```
WhiteSpace

2020-05-04 15:28 UTC, Sen-i commented on src/Collections/PropertyCollection.php
> +
```suggestion

```
WhiteSpace

2020-05-04 15:28 UTC, Sen-i commented on src/Collections/PropertyCollection.php
> +
```suggestion

```
WhiteSpace

2020-05-05 10:39 UTC, Sen-i requested changes

2020-05-05 10:39 UTC, Sen-i commented on src/Hydrators/PropertyHydrator.php
>          $query = $this->database->query("SELECT `Address1`, `Town`, `propertyType`, `Status`, `id`,  `Image` FROM `properties`;");
Field name don't match table.
also I believe that you should link the status and types tables to the properties table and use the respective field names.

2020-05-05 11:16 UTC, amandahrdmn approved these changes

2020-05-05 11:17 UTC, merged